---
# This is configuration file for font builder and other support scripts.
# Format is descriped below.
#
#
# # metadata, to generate demo & fontello info dialogs
# meta:
#
#  author: Daniel Buce
#  homepage: http://...
#  email: ...
#  twitter: http://twitter.com/...
#  dribble: http://dribbble.com/...
#  license: SIL
#  license_url: http://scripts.sil.org/OFL
#
#   css-prefix: "icon-"             # prefix for css-generated classes
#   demo-columns: 4                 # used for html demo page generation
#
# # Font headers. All vars from here will be used as font
# # params in fontforge http://fontforge.sourceforge.net/python.html
# font:
#
#   version: "1.0"
#
#   # use !!!small!!! letters a-z, or Opera will fail under OS X
#   # fontname will be also used as file name.
#   fontname: myfont
#
#   fullname: MyFont
#   familyname: Myfont
#
#   copyright: Copyright (C) 2012 by xxxxxxxx
#
#   ascent: 1638
#   descent: 410
#   weight: Regular
#
#
# #
# # Optional. You can apply global rescale + offset to all font glyphs.
# # Param values ar 0..1, where 1 = 100%. 
# #
# transform:
#   baseline: 0.2                 # baseline for rescale symmetry. Default value
#                                 # calculated from ascent/decsent
#   rescale: 0.68                 # rescale glyphs and center around baseline
#   offset: -0.1                  # shift up/down
#
# glyphs:
#   - file: glyph1_file           # file name, without extention
#     from: 0xNNN                 # Source code for remapper or merge tool
#     code: 0xNNN                 # Symbol code 0x - hex
#     css: icon-gpyph1-name       # For generated CSS
#     search: [word1, word2]      # Search aliases (array). CSS name will be
#                                 # included automatically
#     src: first_font_alias       # alias to font for merge tool
#                                 # list of aliases in src_fonts section
#
#     #
#     # local transformations, only for this glyph (optional)
#     #
#     transform:                  # personal glyph transformation.
#       rescale_rel               # *_rel - applyed after global.
#       offset: 0.2               # without *_rel - override global
#
# #
# # Fonts aliases used only in font merge tool
# #
# src_fonts:
#   first_font_alias: "/absolute/path/to/first/font.ttf"
#
################################################################################
#


meta:
  author: CDC
  homepage: http://CDC.tencent.com
  email: isux@qq.com
  twitter: http://t.qq.com/tencent_cdc
  github: https://github.com/qianduan/qq-hd.font
  license: SIL
  #license_url: http://creativecommons.org/licenses/by/3.0/

  css_prefix_text: "icon-"
  columns: 4

#transform:
#  baseline: 0.5
#  rescale: 1.053
#  # offset: -0.05


font:
  version: "1.0"

  fontname: qzone-touch

  fullname: qzone-touch
  familyname: qzone-touch

  copyright: Copyright (C) 2013 by isux qzone team

  ascent: 850
  descent: 150
  weight: "Regular"


glyphs:

  -
    css: home
    code: 0xe802
    uid: 463217989ae61bf2e906c192b6fc4eb8
    meta:
      author: isux
      email: isux@qq.com
    search: [home]
  -
    css: setting
    code: 0xe803
    uid: edb79a65345ed756d1a827c52ceae89b
    meta:
      author: isux
      email: isux@qq.com
    search: [setting]
  -
    css: add
    code: 0xe804
    uid: 4822fd69742688cacafa92bdfdd039b2
    meta:
      author: isux
      email: isux@qq.com
    search: [add]
  -
    css: arrow-top
    code: 0xe805
    uid: de064a1f23c18e057aa5de9bd0c47cee
    meta:
      author: isux
      email: isux@qq.com
    search: [arrow,top]
  -
    css: arrow-left
    code: 0xe806
    uid: ddeb384e2af65af97800c27c20116fc7
    meta:
      author: isux
      email: isux@qq.com
    search: [arrow,left]
  -
    css: arrow-down
    code: 0xe807
    uid: 163ad4b434e7e66a27c250b4999f5741
    meta:
      author: isux
      email: isux@qq.com
    search: [arrow,down]
  -
    css: arrow-right
    code: 0xe808
    uid: 28e8e05d9213655d629bc60571196cec
    meta:
      author: isux
      email: isux@qq.com
    search: [arrow,right]
  -
    css: circle-down
    code: 0xe809
    uid: 3ae6c56bcf54c4c16bfcd6b18cbdfb72
    meta:
      author: ISUX
      email: isux@qq.com
    search: [cicle,down]
  -
    css: circle-top
    code: 0xe811
    uid: 8c9bc4be8ba9acac80ad3a1c43003583
    meta:
      author: isux
      email: isux@qq.com
    search: [circle,top]
  -
    css: circle-left
    code: 0xe810
    uid: 9eef65b86facc502866e0b096bf819b8
    meta:
      author: isux
      email: isux@qq.com
    search: [circle,left]
  -
    css: circle-right
    code: 0xe80a
    uid: 3bcc637fde77ab3c0ef4cfeb26c3cd01
    meta:
      author: isux
      email: isux@qq.com
    search: [circle,right]
  -
    css: comment
    code: 0xe80b
    uid: 39e9512951742f75159a34cd4bfbf3bd
    meta:
      author: isux
      email: isux@qq.com
    search: [comment]
  -
    css: dairy
    code: 0xe80c
    uid: d88031b5cc3c8be0324d03d08ad648a1
    meta:
      author: isux
      email: isux@qq.com
    search: [dairy]
  -
    css: delete
    code: 0xe80d
    uid: 66790de2da347f0dc5dd24f5dd1bb795
    meta:
      author: isux
      email: isux@qq.com
    search: [delete]
  -
    css: emotion
    code: 0xe80e
    uid: 099a9679e685b8edb46e5c97e6389bf0
    meta:
      author: isux
      email: isux@qq.com
    search: [emotion]
  -
    css: image-upload
    code: 0xe80f
    uid: 5ef8b4fc20c8419f3a28b158b9b30239
    meta:
      author: isux
      email: isux@qq.com
    search: [image,upload]
  -
    css: location
    code: 0xe812
    uid: c56ffd813438e01df23bd781e086b1b1
    meta:
      author: ISUX
      email: isux@qq.com
    search: [location]
  -
    css: love
    code: 0xe813
    uid: 34b703fa72a3ae9c54d3e7a7263e5530
    meta:
      author: isux
      email: isux@qq.com
    search: [love]
  -
    css: love2
    code: 0xe814
    uid: a6f8e6ff93c55b6a5c30ef29b2835302
    meta:
      author: isux
      email: isux@qq.com
    search: [love]
  -
    css: more
    code: 0xe815
    uid: d958dd4749f5931e87a9cf7bd05ed7a7
    meta:
      author: isux
      email: isux@qq.com
    search: [more]

  -
    css: reply
    code: 0xe816
    uid: ed66d17d65f81ce9bfb4b767d52849b2
    meta:
      author: isux
      email: isux@qq.com
    search: [reply]
  -
    css: retweet
    code: 0xe817
    uid: 79f34841d098b3b1e104b14b4b726db1
    meta:
      author: isux
      email: isux@qq.com
    search: [retweet]
  -
    css: share
    code: 0xe818
    uid: c393205fdc844d6b8c04d796cb69e3cc
    meta:
      author: isux
      email: isux@qq.com
    search: [share]
  -
    css: search
    code: 0xe819
    uid: 42227c1732abd97cf82804cf2b47c2bd
    meta:
      author: isux
      email: isux@qq.com
    search: [search]
  -
    css: success
    code: 0xe81a
    uid: 301c32c55704399a5ba0872323a67e64
    meta:
      author: isux
      email: isux@qq.com
    search: [success]
  -
    css: warning
    code: 0xe81b
    uid: f488fb566cbeb40bf83fed66761db166
    meta:
      author: isux
      email: isux@qq.com
    search: [warning]
  -
    css: at
    code: 0xe81c
    uid: 0fbc5fb9da3399f9016cf54cd1e33b14
    meta:
      author: isux
      email: isux@qq.com
    search: [at]
  -
    css: weibo
    code: 0xe81d
    uid: 73eed34411f13b2d9359352e1b3f4653
    meta:
      author: isux
      email: isux@qq.com
    search: [weibo]
  -
    css: write
    code: 0xe81f
    uid: deebe8d2325b0e6bb8e67e759014cd89
    meta:
      author: isux
      email: isux@qq.com
    search: [write]
